### ISSUE TITLE
what is the ST.run method? broken documentation?

### ISSUE THREAD

**Issue by srghma** [purescript/purescript-foreign-object#11]
here

https://github.com/purescript/purescript-foreign-object/blob/8a7dc21c48e3e6d31e253b0e58dd95a3bbd7f6e7/src/Foreign/Object.purs#L78

**Comment by hdgarrood** [comment]
It refers to https://pursuit.purescript.org/packages/purescript-st/4.0.2/docs/Control.Monad.ST#v:run
