### ISSUE TITLE
Add `fromFoldableWithIndex`

### ISSUE THREAD

**Issue by pete-murphy** [purescript/purescript-foreign-object#29]
I've seen it mentioned a [couple](https://discord.com/channels/864614189094928394/865617619464749081/887326007105814548) [times](https://discord.com/channels/864614189094928394/867149806178664478/1032345440248668242) in the Discord that `Object.fromFoldableWithIndex` could be a useful addition, although maybe there's a reason this doesn't exist yet that I'm overlooking?

**Comment by JordanMartinez** [comment]
No idea. Maybe it was overlooked?
